# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3364618f8f865ef95d6959696ec892ccd63169c35c581feea7369b43e4ad29eeb707a3232861eaac24a41573517b37df3d61bcaa80c3d696c3d0a71e5c35319a

test:
  secret_key_base: fbc15dfd1797799fbfcff58584198759aad38ef62e40705343f908389a0eb33e01fa6b8cf8b10c779fe32f74a6099dcca861548dbdff35876e6e437064c116cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
